kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-user-view
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  namespace: api
  name: f94f7e6e-7a64-4bf0-aa75-3aa5f05204a5
  apiGroup: rbac.authorization.k8s.io