apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: openhack-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi/healthcheck
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips/healthcheck
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user/healthcheck
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java/healthcheck