apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: userprofile
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - image: registryumr6730.azurecr.io/tripinsights/userprofile:1.0
        imagePullPolicy: IfNotPresent
        name: userprofile
        env:
        - name: SQL_USER
          value: "sqladminbWu2329"
        - name: SQL_PASSWORD
          value: "zU5qu2Hu9"
        - name: SQL_SERVER
          value: "sqlserverbwu2329.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 80
          name: userprofile
          protocol: TCP
        resources: {}       
      
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: userprofile
