apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: poi
          image: registryumr6730.azurecr.io/tripinsights/poi:1.4
          env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: SQLUSER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-password
                key: SQLPASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql-server
                key: SQLSERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql-dbname
                key: SQLDBNAME
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          resources: {}
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname
          nodePublishSecretRef:
              name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
    - port: 8089
      targetPort: web
  selector:
    app: poi
---