  
# This is SecretProviderClass example using service-principal for authentication with Key Vault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  secretObjects:
  - secretName: sql-user
    type: Opaque
    labels:
      environment: "SQL_USER"
    data:
    - objectName: "sqluseralias"
      key: "SQLUSER"
  - secretName: sql-password
    type: Opaque
    labels:
      environment: "SQL_PASSWORD"
    data:
    - objectName: "sqlpasswordalias"
      key: "SQLPASSWORD"
  - secretName: sql-server
    type: Opaque
    labels:
      environment: "SQL_SERVER"
    data:
    - objectName: "sqlserveralias"
      key: "SQLSERVER"
  - secretName: sql-dbname
    type: Opaque
    labels:
      environment: "SQL_DBNAME"
    data:
    - objectName: "sqldbnamealias"
      key: "SQLDBNAME"
  parameters:
    userAssignedIdentityID: "8d781073-67c4-420f-8a71-b11bea4acc73"
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "trips-secrets"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQLUSER
          objectType: secret
          objectAlias: "sqluseralias"
        - |
          objectName: SQLPASSWORD
          objectType: secret
          objectAlias: "sqlpasswordalias"
        - |
          objectName: SQLSERVER
          objectType: secret
          objectAlias: "sqlserveralias"
        - |
          objectName: SQLDBNAME
          objectType: secret
          objectAlias: "sqldbnamealias"
    resourceGroup: "teamResources"
    subscriptionId: "878db795-8002-456c-9841-bc2c43b269ea"
    directoryId: "77a35d5b-05ab-466c-8a95-5290df1492fd"
    tenantId: "77a35d5b-05ab-466c-8a95-5290df1492fd"