apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: trips
          image: registryumr6730.azurecr.io/tripinsights/trips:1.0
          env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql-user
                key: SQLUSER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-password
                key: SQLPASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql-server
                key: SQLSERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql-dbname
                key: SQLDBNAME
          - name: OPENAPI_DOCS_URI
            value: "http://$EXTERNAL_IP"
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store-2"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: azure-kvname
              nodePublishSecretRef:
                name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  ports:
    - port: 8082
      targetPort: http
  selector:
    app: trips
---