apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: user-java
        image: registryumr6730.azurecr.io/tripinsights/user-java:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-user
              key: SQLUSER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: SQLPASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sql-server
              key: SQLSERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sql-dbname
              key: SQLDBNAME
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        resources: {}       
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kvname
          nodePublishSecretRef:
              name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api  
spec:
  ports:
  - port: 8081
    targetPort: http
  selector:
    app: user-java